### ISSUE TITLE
iOS: SignInButton doesn't open Warpcast; breaks auth flow.

### ISSUE THREAD

**Issue by jtgi** [farcasterxyz/auth-monorepo#108]
**What is the bug?**
On iOS Safari after the Sign In button is clicked, if the time between the redirect and the click is too long, the Warpcast deep link does not work. There's no recovering the auth flow when that happens.

**How can it be reproduced? (optional)**
https://github.com/farcasterxyz/auth-monorepo/assets/2442166/867b29c3-0773-4cf1-baf3-b275d2307a1f
- Open https://sign-in-with-farcaster-demo.replit.app/ on iOS Safari with Warpcast installed
- Click sign in
**expect**: it should open the Warpcast app and prompt for approval
**actual**: loads a new safari tab prompting to "Install Warpcast", the auth flow cannot be recovered, even if you open the Warpcast manually and approve.

**Additional context (optional)**
- iOS deep links will not open the app if the time from user interaction (mouse click) to a redirect is too slow.
- In authkit's case, the time to setup the channel after clicking sign up is enough to break the deep link and the whole auth flow.
- I am based in Asia, so if you cannot reproduce try fudging your latency

**Possible Solutions**
- if iOS on sign in button click, create the channel *then* show a dialog with another button to open the app (or some variant), see example below, adds second state to button once channel is created.

https://github.com/farcasterxyz/auth-monorepo/assets/2442166/4750a5ce-feeb-44a1-974b-83c3c2be565e

e.g.
```diff
diff --git a/packages/auth-kit/src/components/SignInButton/SignInButton.tsx b/packages/auth-kit/src/components/SignInButton/SignInButton.tsx
index 9d85c03..b31d036 100644
--- a/packages/auth-kit/src/components/SignInButton/SignInButton.tsx
+++ b/packages/auth-kit/src/components/SignInButton/SignInButton.tsx
@@ -3,7 +3,7 @@ import useSignIn, { UseSignInArgs } from "../../hooks/useSignIn.ts";
 import { ActionButton } from "../ActionButton/index.ts";
 import { ProfileButton } from "../ProfileButton/index.ts";
 import { QRCodeDialog } from "../QRCodeDialog/index.tsx";
-import { isMobile } from "../../utils.ts";
+import { isIOS, isMobile } from "../../utils.ts";
 
 type SignInButtonProps = UseSignInArgs & { debug?: boolean };
 
@@ -12,6 +12,7 @@ export function SignInButton({ debug, ...signInArgs }: SignInButtonProps) {
   const { signIn, reconnect, isSuccess, isError, error, url, data, validSignature } = signInState;
 
   const [showDialog, setShowDialog] = useState(false);
+  const [showIOSButton, setShowIOSButton] = useState(false);
 
   const onClick = useCallback(() => {
     isError ? reconnect() : signIn();
@@ -22,7 +23,11 @@ export function SignInButton({ debug, ...signInArgs }: SignInButtonProps) {
 
   useEffect(() => {
     if (url && isMobile()) {
-      window.location.href = url;
+      if (!isIOS()) {
+        window.location.href = url;
+      } else {
+        setShowIOSButton(true);
+      }
     }
   }, [url, setShowDialog]);
 
@@ -32,7 +37,9 @@ export function SignInButton({ debug, ...signInArgs }: SignInButtonProps) {
         <ProfileButton userData={data} />
       ) : (
         <>
-          <ActionButton onClick={onClick} label="Sign in" />
+          {showIOSButton
+            ? <ActionButton onClick={() => { window.location.href = url! }} label="Open App" />
+            : <ActionButton onClick={onClick} label="Sign in" />}
           {url && (
             <QRCodeDialog
               open={showDialog && !isMobile()}
```

thanks for farcaster

**Comment by deodad** [comment]
Thanks for reporting. When I went through this on my phone I was taken to the web page as you descriped, but I did have this option to open the Warpcast app, which took me into the app and the sign in screen.

Just to clarify, did you have this top bar that allows for "Open in the Warpcast app"?

![IMG_ED9C8693D4E5-1](https://github.com/farcasterxyz/auth-monorepo/assets/1143517/71a8c09c-fcd6-4edd-9da2-aac0740c78f8)

**Comment by jtgi** [comment]
Yep, it shows the native banner at the top to sign in but even after
opening it, then approving sign in Warpcast, manually going back to the
app, the auth flow doesn’t complete.

I attached a link to a video demonstrating this in the second reproduction
section.
